"use client";
import Head from "next/head";
import { Inter } from "next/font/google";
import IdeaToProtoTypeHeader from "../../../../../components/Service/IdeaToProtoTypeHeader";
import InterActiveProtoType from "../../../../../components/Service/InterActiveProtoType";
import ApproachOurProject from "../../../../../components/Service/ApproachOurProject";
import Collaborate from "../../../../../components/Collabrate";
import PortFolio from "../../../../../components/Service/PortFolio";
import { useEffect, useState } from "react";
import { headerStore } from "@/store/headerStore";
import Header from "components/Header";

export default function IdeaToProtoType() {
  let isScrolled = headerStore((store) => store.isScrolled);
  const update = headerStore((store) => store.update);
  console.log(isScrolled);

  useEffect(() => {
    const handleScrollView = () => {
      if (window.scrollY >= 50) {
        update(true);
      } else {
        update(false);
      }
    };

    window.addEventListener("scroll", handleScrollView);
    return () => {
      window.removeEventListener("scroll", handleScrollView);
    };
  }, [update]);

  return (
    <>
      <div>
        <Head>
          <title>Idea To Prototype | Dewallstreet Consultancy </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <main>
        <IdeaToProtoTypeHeader />
        <InterActiveProtoType />
        <ApproachOurProject />
        <PortFolio />
        <Collaborate
          title="You’re one step away from making your ideas into reality."
          textAlign="center"
          heading="BENEFITS"
        />
      </main>
    </>
  );
}
