import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/impact.module.scss";
import Company from "../../components/company";
import Founder from "../../components/FounderSlider";

const inter = Inter({ subsets: ["latin"] });

export default function Impact() {
  return (
    <>
      <Head>
        <title>Impact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.impacts_home}>
          <div className={styles.mx}>
            <div className={styles.impact_hero}>
              <div className={styles.hero_wrapper}>
                <Image
                  className={styles.member}
                  src={"/assets/images/members.png"}
                  alt="members"
                  width={583}
                  height={496}
                />

                <div className={styles.group_img}>
                  <Image
                    src={"/assets/images/group-img.png"}
                    alt="members"
                    width={310}
                    height={264}
                  />
                </div>
                <div className={styles.explain}>
                  <h4>
                    Transformation we cause in the industry, aren’t via big
                    moves, but significantly smaller actions, which we believe,
                    is heading us into what it is to become the great, and be
                    called the novel and disruptive.
                  </h4>
                </div>
                <div className={styles.border_right}></div>
              </div>
              <Founder />
            </div>
            <div className={styles.border_bottom}></div>
            <Company />
          </div>
        </div>
      </main>
    </>
  );
}
