import Head from "next/head";
import { Inter } from "next/font/google";
import ApproachOurProject from "../../components/Service/ApproachOurProject";
import IdeaToProtoTypeHeader from "../../components/Service/IdeaToProtoTypeHeader";
import InterActiveProtoType from "../../components/Service/InterActiveProtoType";
import PortFolio from "../../components/Service/PortFolio";

const inter = Inter({ subsets: ["latin"] });

export default function StartupUxServices() {
  return (
    <>
      <Head>
        <title>StartupUxServices</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IdeaToProtoTypeHeader />
        <InterActiveProtoType />
        <ApproachOurProject />
        <PortFolio />
      </main>
    </>
  );
}
